[package]
name = "agent2d-pipeline"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
agent2d-core = { path = "../agent2d-core" }
agent2d-compression = { path = "../agent2d-compression" }
agent2d-sr = { path = "../agent2d-sr" }
tempfile = "3"
uuid.workspace = true

[dev-dependencies]
image.workspace = true
